# Generated by Django 4.1.7 on 2023-03-25 18:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterProficience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('page', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRealm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('mastery', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='helper.skillmastery')),
            ],
            options={
                'verbose_name_plural': 'character Skills',
            },
        ),
        migrations.CreateModel(
            name='Proficience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('apprentice', 'apprentice'), ('user', 'user'), ('fighter', 'fighter'), ('warrior', 'warrior'), ('veteran', 'veteran'), ('master', 'master'), ('gran-master', 'gran-master'), ('king', 'king'), ('emperor', 'emperor'), ('saint', 'saint')], max_length=20)),
                ('learning', models.SmallIntegerField()),
                ('damage', models.SmallIntegerField()),
                ('control', models.SmallIntegerField()),
                ('aura', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(50)])),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_position', models.SmallIntegerField()),
                ('rank', models.CharField(max_length=20)),
                ('bonus_physic', models.SmallIntegerField()),
                ('limit_spiritual', models.SmallIntegerField()),
                ('bonus_spiritual', models.SmallIntegerField()),
                ('limit_physic', models.SmallIntegerField()),
                ('description', models.TextField(default='N/A')),
            ],
            options={
                'verbose_name_plural': 'Realms',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STR', models.SmallIntegerField(default=0)),
                ('AGI', models.SmallIntegerField(default=0)),
                ('DEX', models.SmallIntegerField(default=0)),
                ('RES', models.SmallIntegerField(default=0)),
                ('CON', models.SmallIntegerField(default=0)),
                ('KY', models.SmallIntegerField(default=0)),
                ('CTL', models.SmallIntegerField(default=0)),
                ('PERCEPTION', models.SmallIntegerField(default=0)),
                ('page', models.SmallIntegerField(default=0)),
                ('fk_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters')),
            ],
            options={
                'verbose_name_plural': 'Status Entries',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_skill', models.CharField(choices=[('fundation', 'fundation'), ('skill', 'skill')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('comum', 'comum'), ('incomum', 'incomum'), ('rara', 'rara'), ('ancia', 'ancia'), ('legendaria', 'legendaria'), ('cobre', 'cobre'), ('ferro', 'ferro'), ('prata', 'prata'), ('ouro', 'ouro'), ('ferro negro', 'ferro negro'), ('ouro de iril', 'ouro de iril'), ('bronze selestial', 'bronze selestial'), ('ferro vulcanico', 'ferro vulcanico'), ('alomanium', 'alomanium'), ('frost metal', 'metal gelico'), ('abyss silver', 'prata abrissal'), ('metal morilitico', 'metal morilitico'), ('draconian steel', 'aço draconiana'), ('mitril', 'mitril')], max_length=20)),
                ('sub_rank', models.CharField(choices=[('low', 'low'), ('middle', 'middle'), ('upper', 'upper'), ('peak', 'peak')], max_length=6)),
                ('description', models.TextField()),
                ('bonus_status', models.CharField(max_length=20)),
                ('time', models.SmallIntegerField()),
                ('bonus_1', models.SmallIntegerField()),
                ('bonus_2', models.SmallIntegerField()),
                ('bonus_3', models.SmallIntegerField()),
                ('bonus_4', models.SmallIntegerField()),
                ('bonus_5', models.SmallIntegerField()),
                ('weapon_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.weaponstype')),
            ],
        ),
        migrations.CreateModel(
            name='Murim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_realm', models.PositiveSmallIntegerField(default=0)),
                ('fk_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.characters')),
                ('fk_proficience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='murim.characterproficience')),
                ('fk_realm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='murim.characterrealm')),
                ('fk_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='murim.characterskills')),
                ('fk_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='murim.status')),
            ],
        ),
        migrations.AddField(
            model_name='characterskills',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murim.skills'),
        ),
        migrations.AddField(
            model_name='characterrealm',
            name='fk_realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murim.realms'),
        ),
        migrations.AddField(
            model_name='characterproficience',
            name='fk_murim',
            field=models.ManyToManyField(through='murim.Murim', to='character.characters'),
        ),
        migrations.AddField(
            model_name='characterproficience',
            name='fk_proficience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murim.proficience'),
        ),
        migrations.AddField(
            model_name='characterproficience',
            name='weapon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.weaponstype'),
        ),
    ]
