# Generated by Django 4.1.7 on 2023-03-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_characters_img'),
        ('murim', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Atributes',
        ),
        migrations.AddField(
            model_name='characterrealm',
            name='rank',
            field=models.CharField(choices=[('beggin', 'beggin'), ('middle', 'middle'), ('upper', 'upper')], default='middle', max_length=15),
            preserve_default=False,
        ),
    ]
