# Generated by Django 4.1.7 on 2023-03-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_characters_img'),
        ('murim', '0002_rename_status_atributes_characterrealm_rank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atributes',
            new_name='Atribute',
        ),
        migrations.AlterModelOptions(
            name='atribute',
            options={'verbose_name_plural': 'Atributes'},
        ),
    ]
