# Generated by Django 4.1.7 on 2023-03-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_characters_img'),
        ('murim', '0003_rename_atributes_atribute_alter_atribute_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterskills',
            old_name='skill_id',
            new_name='fk_skill',
        ),
        migrations.AddField(
            model_name='characterskills',
            name='fk_character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='character.characters'),
            preserve_default=False,
        ),
    ]
