# Generated by Django 4.1.7 on 2023-03-30 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_characters_img'),
        ('murim', '0004_rename_skill_id_characterskills_fk_skill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterskills',
            options={'ordering': ['-mastery'], 'verbose_name_plural': 'Character Skills'},
        ),
        migrations.AddField(
            model_name='characterrealm',
            name='fk_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.characters'),
        ),
        migrations.AlterField(
            model_name='characterrealm',
            name='rank',
            field=models.CharField(choices=[('beggin', 'beggin'), ('middle', 'middle'), ('upper', 'upper'), ('peak', 'peak')], max_length=15),
        ),
    ]
