# Generated by Django 4.1.7 on 2023-03-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_characters_img'),
        ('murim', '0005_alter_characterskills_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realms',
            options={'ordering': ['rank_position'], 'verbose_name_plural': 'Realms'},
        ),
        migrations.RemoveField(
            model_name='characterproficience',
            name='fk_murim',
        ),
        migrations.AddField(
            model_name='characterproficience',
            name='fk_character',
            field=models.ManyToManyField(through='murim.Murim', to='character.characters'),
        ),
    ]
