# Generated by Django 4.1.7 on 2023-03-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_characters_img'),
        ('murim', '0006_alter_realms_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterproficience',
            name='fk_character',
        ),
        migrations.AddField(
            model_name='characterproficience',
            name='fk_character',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='character.characters'),
            preserve_default=False,
        ),
    ]
