# Generated by Django 4.1.7 on 2023-03-08 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helper', '0004_economy_remove_localization_descrition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('population', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('economy', models.ManyToManyField(to='helper.economy')),
                ('fk_kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.kingdom')),
                ('localization', models.ManyToManyField(to='helper.localization')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('fk_kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.kingdom')),
                ('localization', models.ManyToManyField(to='helper.localization')),
            ],
        ),
        migrations.CreateModel(
            name='Fief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.SmallIntegerField()),
                ('description', models.TextField()),
                ('fk_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.kingdom')),
                ('localization', models.ManyToManyField(to='helper.localization')),
            ],
        ),
    ]
