# Generated by Django 4.1.7 on 2023-03-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.countrytype')),
            ],
        ),
        migrations.CreateModel(
            name='Fief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('economy', models.ManyToManyField(to='helper.economy')),
                ('fk_fief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.fief')),
                ('localization', models.ManyToManyField(to='helper.localization')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('fk_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.country')),
                ('localization', models.ManyToManyField(to='helper.localization')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='N/A')),
                ('fk_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.country')),
                ('fk_fief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.fief')),
                ('fk_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.region')),
                ('fk_settlement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.settlement')),
                ('localization', models.ManyToManyField(to='helper.localization')),
                ('resource', models.ManyToManyField(blank=True, to='helper.resource')),
            ],
        ),
        migrations.AddField(
            model_name='fief',
            name='fk_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.region'),
        ),
        migrations.AddField(
            model_name='fief',
            name='localization',
            field=models.ManyToManyField(to='helper.localization'),
        ),
    ]
