# Generated by Django 4.1.7 on 2023-03-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.SmallIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.SmallIntegerField(choices=[])),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('population', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('economy', models.ManyToManyField(to='helper.economy')),
                ('fk_kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.kingdom')),
                ('localization', models.ManyToManyField(to='helper.localization')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('fk_kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.kingdom')),
                ('localization', models.ManyToManyField(to='helper.localization')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('fk_fief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.fief')),
                ('fk_kingdom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.kingdom')),
                ('fk_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.region')),
                ('fk_settlement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.settlement')),
            ],
        ),
        migrations.AddField(
            model_name='fief',
            name='fk_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.kingdom'),
        ),
        migrations.AddField(
            model_name='fief',
            name='localization',
            field=models.ManyToManyField(to='helper.localization'),
        ),
    ]
