# Generated by Django 4.1.7 on 2023-03-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_alter_kingdom_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('fk_fief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.fief')),
                ('fk_kingdom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.kingdom')),
                ('fk_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.region')),
                ('fk_settlement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.settlement')),
            ],
        ),
    ]
