# Generated by Django 4.1.7 on 2023-02-28 00:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(default='N/A', max_length=50)),
                ('birth_year', models.SmallIntegerField()),
                ('season', models.CharField(max_length=30)),
                ('periode', models.CharField(max_length=15)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STR', models.SmallIntegerField()),
                ('AGI', models.SmallIntegerField()),
                ('DEX', models.SmallIntegerField()),
                ('RES', models.SmallIntegerField()),
                ('CON', models.SmallIntegerField()),
                ('KY', models.SmallIntegerField()),
                ('CTL', models.SmallIntegerField()),
                ('PER', models.SmallIntegerField()),
                ('page', models.SmallIntegerField()),
                ('fk_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('comum', 'comum'), ('incomum', 'incomum'), ('rara', 'rara'), ('ancia', 'ancia'), ('legendaria', 'legendaria'), ('cobre', 'cobre'), ('ferro', 'ferro'), ('prata', 'prata'), ('ouro', 'ouro'), ('ferro negro', 'ferro negro'), ('ouro de iril', 'ouro de iril'), ('ferro vulcanico', 'ferro vulcanico'), ('bronze selestial', 'bronze selestial'), ('alomanium', 'alomanium'), ('frost metal', 'metal gelico'), ('abyss silver', 'prata abrissal'), ('metal morilitico', 'metal morilitico'), ('draconian steel', 'aço draconiana'), ('mitril', 'mitril')], max_length=20)),
                ('sub_rank', models.CharField(choices=[('low', 'low'), ('middle', 'middle'), ('upper', 'upper'), ('peak', 'peak')], max_length=6)),
                ('mastery', models.CharField(choices=[('apprentice', 'apprentice'), ('user', 'user'), ('fighter', 'fighter'), ('warrior', 'warrior'), ('veteran', 'veteran'), ('master', 'master'), ('gran-master', 'gran-master'), ('king', 'king'), ('emperor', 'emperor'), ('saint', 'saint')], max_length=15)),
                ('page', models.SmallIntegerField()),
                ('fk_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('gate', 'gate'), ('garthering', 'garthering'), ('growing', 'growing'), ('control', 'control'), ('small-opening', 'small-opening'), ('fundation', 'fundation'), ('reforje', 'reforje'), ('revitalization', 'revitalization'), ('gran-opening', 'gran-opening'), ('rebirth', 'rebirth'), ('contruction', 'contruction'), ('espititualization', 'espititualization'), ('elementarization', 'elementarization'), ('elemetal mastery', 'elemetal mastery'), ('elemental king', 'elemental king')], max_length=20)),
                ('page', models.SmallIntegerField()),
                ('fk_character', models.ManyToManyField(to='character.characters')),
            ],
        ),
        migrations.CreateModel(
            name='Proficience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(choices=[('sword', 'sword'), ('spear', 'spear'), ('axe', 'axe'), ('dagger', 'dagger'), ('bow', 'bow'), ('unarmed', 'unarmed'), ('shield', 'shield'), ('mace', 'mace')], max_length=20)),
                ('mastery', models.CharField(choices=[('apprentice', 'apprentice'), ('user', 'user'), ('fighter', 'fighter'), ('warrior', 'warrior'), ('veteran', 'veteran'), ('master', 'master'), ('gran-master', 'gran-master'), ('king', 'king'), ('emperor', 'emperor'), ('saint', 'saint')], max_length=15)),
                ('level', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('page', models.SmallIntegerField()),
                ('fk_character', models.ManyToManyField(to='character.characters')),
            ],
        ),
    ]
