# Generated by Django 4.1.7 on 2023-03-12 23:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterProficience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('page', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRealm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(default='images/character/default.png', upload_to='images/character/')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(default='N/A', max_length=50)),
                ('birth_year', models.SmallIntegerField()),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('description', models.TextField(default='olá eu sou goku', null=True)),
                ('periode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.periode')),
            ],
            options={
                'verbose_name_plural': 'Character Entries',
            },
        ),
        migrations.CreateModel(
            name='Proficience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('apprentice', 'apprentice'), ('user', 'user'), ('fighter', 'fighter'), ('warrior', 'warrior'), ('veteran', 'veteran'), ('master', 'master'), ('gran-master', 'gran-master'), ('king', 'king'), ('emperor', 'emperor'), ('saint', 'saint')], max_length=20)),
                ('learning', models.SmallIntegerField()),
                ('damage', models.SmallIntegerField()),
                ('control', models.SmallIntegerField()),
                ('aura', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(50)])),
            ],
        ),
        migrations.CreateModel(
            name='Realms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_position', models.SmallIntegerField()),
                ('rank', models.CharField(choices=[('gate', 'gate'), ('garthering', 'garthering'), ('growing', 'growing'), ('control', 'control'), ('small-opening', 'small-opening'), ('fundation', 'fundation'), ('reforje', 'reforje'), ('revitalization', 'revitalization'), ('gran-opening', 'gran-opening'), ('rebirth', 'rebirth'), ('contruction', 'contruction'), ('espititualization', 'espititualization'), ('elementarization', 'elementarization'), ('elemetal mastery', 'elemetal mastery'), ('elemental king', 'elemental king')], max_length=20)),
                ('bonus_physic', models.SmallIntegerField()),
                ('limit_spiritual', models.SmallIntegerField()),
                ('bonus_spiritual', models.SmallIntegerField()),
                ('limit_physic', models.SmallIntegerField()),
                ('description', models.TextField(default='N/A')),
            ],
            options={
                'verbose_name_plural': 'Realms',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_skill', models.CharField(choices=[('fundation', 'fundation'), ('skill', 'skill')], max_length=20)),
                ('weapon_type', models.SmallIntegerField(choices=[])),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('comum', 'comum'), ('incomum', 'incomum'), ('rara', 'rara'), ('ancia', 'ancia'), ('legendaria', 'legendaria'), ('cobre', 'cobre'), ('ferro', 'ferro'), ('prata', 'prata'), ('ouro', 'ouro'), ('ferro negro', 'ferro negro'), ('ouro de iril', 'ouro de iril'), ('bronze selestial', 'bronze selestial'), ('ferro vulcanico', 'ferro vulcanico'), ('alomanium', 'alomanium'), ('frost metal', 'metal gelico'), ('abyss silver', 'prata abrissal'), ('metal morilitico', 'metal morilitico'), ('draconian steel', 'aço draconiana'), ('mitril', 'mitril')], max_length=20)),
                ('sub_rank', models.CharField(choices=[('low', 'low'), ('middle', 'middle'), ('upper', 'upper'), ('peak', 'peak')], max_length=6)),
                ('description', models.TextField()),
                ('bonus_status', models.CharField(max_length=20)),
                ('time', models.SmallIntegerField()),
                ('bonus_1', models.SmallIntegerField()),
                ('bonus_2', models.SmallIntegerField()),
                ('bonus_3', models.SmallIntegerField()),
                ('bonus_4', models.SmallIntegerField()),
                ('bonus_5', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STR', models.SmallIntegerField()),
                ('AGI', models.SmallIntegerField()),
                ('DEX', models.SmallIntegerField()),
                ('RES', models.SmallIntegerField()),
                ('CON', models.SmallIntegerField()),
                ('KY', models.SmallIntegerField()),
                ('CTL', models.SmallIntegerField()),
                ('PER', models.SmallIntegerField()),
                ('page', models.SmallIntegerField()),
                ('fk_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters')),
            ],
            options={
                'verbose_name_plural': 'Status Entries',
            },
        ),
        migrations.CreateModel(
            name='CharacterSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters')),
                ('mastery', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='helper.skillmastery')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.skills')),
            ],
            options={
                'verbose_name_plural': 'character Skills',
            },
        ),
        migrations.AddField(
            model_name='characters',
            name='proficience',
            field=models.ManyToManyField(through='character.CharacterProficience', to='character.proficience'),
        ),
        migrations.AddField(
            model_name='characters',
            name='realm',
            field=models.ManyToManyField(through='character.CharacterRealm', to='character.realms'),
        ),
        migrations.AddField(
            model_name='characters',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.season'),
        ),
        migrations.AddField(
            model_name='characters',
            name='skills',
            field=models.ManyToManyField(through='character.CharacterSkills', to='character.skills'),
        ),
        migrations.AddField(
            model_name='characterrealm',
            name='fk_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters'),
        ),
        migrations.AddField(
            model_name='characterrealm',
            name='fk_realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.realms'),
        ),
        migrations.AddField(
            model_name='characterproficience',
            name='character_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters'),
        ),
        migrations.AddField(
            model_name='characterproficience',
            name='proficience_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.proficience'),
        ),
        migrations.AddField(
            model_name='characterproficience',
            name='weapon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.weaponstype'),
        ),
    ]
