# Generated by Django 4.1.7 on 2023-03-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(default='images/character/default.png', upload_to='images/character/')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(default='N/A', max_length=50)),
                ('birth_year', models.SmallIntegerField()),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('description', models.TextField(default='olá eu sou goku', null=True)),
                ('periode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.periode')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.season')),
            ],
            options={
                'verbose_name_plural': 'Character Entries',
            },
        ),
        migrations.CreateModel(
            name='TotalGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('updated_page', models.PositiveSmallIntegerField()),
                ('fk_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('page', models.SmallIntegerField()),
                ('fk_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters')),
                ('fk_item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='GoldEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('page', models.PositiveSmallIntegerField()),
                ('fk_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters')),
            ],
        ),
    ]
