# Generated by Django 4.1.7 on 2023-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='alive',
            field=models.CharField(choices=[('alive', 'alive'), ('death', 'death')], default='alive', max_length=20),
            preserve_default=False,
        ),
    ]
