# Generated by Django 4.1.7 on 2023-02-22 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='character',
            new_name='Characters',
        ),
    ]
