# Generated by Django 4.1.7 on 2023-02-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character_birth',
            old_name='character_id',
            new_name='fk_character',
        ),
        migrations.AddField(
            model_name='characters',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
