# Generated by Django 4.1.7 on 2023-02-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_rename_character_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='age',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
