# Generated by Django 4.1.7 on 2023-03-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_books_slug'),
        ('character', '0002_characters_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='fk_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.books'),
        ),
    ]
