# Generated by Django 4.1.7 on 2023-02-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_rename_character_id_character_birth_fk_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
