# Generated by Django 4.1.7 on 2023-03-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_characters_fk_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='img',
            field=models.FileField(default='default/character.png', upload_to='images/character/'),
        ),
    ]
