# Generated by Django 4.1.7 on 2023-03-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_characters_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='img',
            field=models.FileField(default='images/character/default.png', upload_to='images/character/'),
        ),
    ]
