# Generated by Django 4.1.7 on 2023-03-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_skills_weapon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='weapon_type',
            field=models.SmallIntegerField(choices=[(1, 'spear'), (2, 'sword'), (3, 'saber'), (5, 'unarmed'), (4, 'bow')]),
        ),
    ]
