# Generated by Django 4.1.7 on 2023-02-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_alter_characters_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='birth_year',
            field=models.SmallIntegerField(default=712),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='periode',
            field=models.CharField(default=712, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='season',
            field=models.CharField(default=712, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Character_birth',
        ),
    ]
