# Generated by Django 4.1.7 on 2023-03-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_alter_skills_weapon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='bonus_1',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='bonus_2',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='bonus_3',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='bonus_4',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='bonus_5',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='bonus_status',
            field=models.CharField(default='str', max_length=20),
            preserve_default=False,
        ),
    ]
