# Generated by Django 4.1.7 on 2023-02-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_characters_birth_year_characters_periode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proficience',
            old_name='fK_character',
            new_name='fk_character',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='fK_character',
            new_name='fk_character',
        ),
    ]
