# Generated by Django 4.1.7 on 2023-03-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_skills_bonus_1_skills_bonus_2_skills_bonus_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='time',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
