# Generated by Django 4.1.7 on 2023-03-09 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_countrytype_description'),
        ('character', '0008_alter_characterskills_mastery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterskills',
            name='mastery',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='helper.skillmastery'),
        ),
    ]
