# Generated by Django 4.1.7 on 2023-03-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_alter_characterskills_mastery'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='description',
            field=models.TextField(default='olá eu sou goku', null=True),
        ),
    ]
