# Generated by Django 4.1.7 on 2023-03-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_alter_characters_periode_alter_characters_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characters',
            options={'verbose_name_plural': 'Character Entries'},
        ),
        migrations.AddField(
            model_name='characters',
            name='realm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.realms'),
        ),
    ]
