# Generated by Django 4.1.7 on 2023-03-09 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0012_alter_characters_options_characters_realm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='realm',
        ),
        migrations.CreateModel(
            name='CharacterRealm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('fk_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters')),
                ('fk_realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.realms')),
            ],
        ),
        migrations.AddField(
            model_name='characters',
            name='realm',
            field=models.ManyToManyField(through='character.CharacterRealm', to='character.realms'),
        ),
    ]
