# Generated by Django 4.1.7 on 2023-03-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookColection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(max_length=80)),
                ('is_colection', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('murim', 'murim'), ('fantasy', 'fantasy')], max_length=30)),
                ('colection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.bookcolection')),
            ],
        ),
    ]
