# Generated by Django 4.1.7 on 2023-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_bookcolection_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
    ]
