# Generated by Django 4.1.7 on 2023-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_localization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descrition', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='localization',
            name='descrition',
        ),
    ]
