# Generated by Django 4.1.7 on 2023-03-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_countrytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytype',
            name='description',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
    ]
