# Generated by Django 4.1.7 on 2023-03-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vassals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('fk_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characters')),
                ('fk_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vassal_fk_house', to='geopolitic.house')),
            ],
        ),
        migrations.CreateModel(
            name='VassalHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('fk_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vassalhouse_fk_house', to='geopolitic.house')),
                ('fk_vassal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geopolitic.house')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('fk_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_fk_character', to='character.characters')),
                ('fk_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_fk_house', to='geopolitic.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='house_vassal',
            field=models.ManyToManyField(through='geopolitic.VassalHouse', to='geopolitic.house'),
        ),
        migrations.AddField(
            model_name='house',
            name='members',
            field=models.ManyToManyField(related_name='members', through='geopolitic.Members', to='character.characters'),
        ),
        migrations.AddField(
            model_name='house',
            name='vassals',
            field=models.ManyToManyField(through='geopolitic.Vassals', to='character.characters'),
        ),
    ]
